

# Si sale un error, me aparece un mensaje
try:
    nota = int(input("Ingrese su nota: "))
    print(f'La nota ingresada es {nota}')
except:
    print("Asegurese de ingresar un numero")





